name: Node.js CI

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run affected:apps -- --base=$GITHUB_SHA --target=master
    - run: npm run affected:libs -- --base=$GITHUB_SHA --target=master
    - run: npm run affected:build -- --base=$GITHUB_SHA --target=master
    - run: npm run affected:e2e -- --base=$GITHUB_SHA --target=master
    - run: npm run affected:lint -- --base=$GITHUB_SHA --target=master