name: Node.js CI

on:
  pull_request:
    branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run affected:apps
    - run: npm run affected:libs
    - run: npm run affected:build
    - run: npm run affected:e2e
    - run: npm run affected:lint
